## Installing and Importing Numpy

In [4]:
!pip install numpy

In [6]:
import numpy as np

## Create a Numpy Array (Ndarray)

In [8]:
np.array(11)   # 0 dimentional array

array(11)

In [9]:
np.array([1,2,3,4,5])   # 1 dimensional array

array([1, 2, 3, 4, 5])

In [12]:
x = np.array([1,2,3,4,5])   # 1 dimensional array

In [13]:
x

array([1, 2, 3, 4, 5])

In [15]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9,10])], dtype=object)


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 10]], dtype=object)

In [18]:
np.zeros((3,4), dtype = int)  # (no of rows , no of columns)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.ones(6 , dtype=int)

array([1, 1, 1, 1, 1, 1])

### Identity Matrics

In [28]:
np.eye(3 , dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Arange Function

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### random function

In [26]:
np.random.random((2,3))

array([[0.50626916, 0.5316032 , 0.28863995],
       [0.14323339, 0.83338001, 0.91199211]])

In [27]:
np.random.random((2,3))

array([[0.88604015, 0.53024345, 0.39642786],
       [0.37911987, 0.1971622 , 0.40062075]])

## Array Inspection

In [31]:
arr = np.array([[1,2,3,4],[6,7,8,9]])

In [33]:
arr

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [34]:
arr.shape

(2, 4)

In [36]:
arr = np.array([[1,2,3],[6,7,8]])
arr.shape

(2, 3)

In [37]:
arr

array([[1, 2, 3],
       [6, 7, 8]])

In [38]:
arr.shape = (3,2)
arr

array([[1, 2],
       [3, 6],
       [7, 8]])

In [39]:
arr = np.array([[1,2,3,4],[6,7,8,9]])
arr.shape = (8,1)
arr

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [9]])

In [40]:
ar = np.arange(24)

In [41]:
ar.ndim

1

In [42]:
ar = ar.reshape(12,2)

In [43]:
ar.ndim

2

In [44]:
ar.size

24

In [45]:
zero = np.zeros((3,4))

In [46]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
zero.size

12

In [48]:
zero.ndim

2

In [49]:
zero.shape

(3, 4)

In [50]:
zero.dtype

dtype('float64')

In [51]:
zero = np.zeros((3,4) , dtype = int)

In [52]:
zero.dtype

dtype('int32')

## Array Amthematics

In [53]:
np.sum([1,2,3,4,5])

15

In [54]:
a,b = 10,15
np.sum([a,b])

25

In [ ]:
>>> np.sum([[0, 1], [0, 5]])
6
>>> np.sum([[0, 1], [0, 5]], axis=0)
array([0, 6])
>>> np.sum([[0, 1], [0, 5]], axis=1)

In [55]:
np.sum([[0, 1], [0, 5]])

6

In [57]:
np.array([[0, 1], [0, 5]])

array([[0, 1],
       [0, 5]])

In [56]:
np.sum([[0, 1], [0, 5]], axis=0)    # axis = 0 -> sum across the columns

array([0, 6])

In [58]:
np.sum([[0, 1], [0, 5]], axis=1)   # axis = 1 -> sum across the rows

array([1, 5])

In [59]:
np.subtract(10,9)

1

In [60]:
np.subtract(10,20)

-10

In [61]:
np.multiply(2,3)

6

In [62]:
np.divide(10,5)

2.0

In [63]:
np.divide(10,0)

<ipython-input-63-366f6012c8b8>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(10,0)


inf

In [64]:
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.multiply(a,b)

In [65]:
c

array([ 2,  6, 12])

In [66]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [67]:
print("Sin: ", np.sin(a))
print("Cos: ", np.cos(a))
print("Log: ", np.log(a))

Sin:  [0.84147098 0.90929743 0.14112001]
Cos:  [ 0.54030231 -0.41614684 -0.9899925 ]
Log:  [0.         0.69314718 1.09861229]


### Array Comparison

In [70]:
a = [1,2,3]
b = [2,3,4]
c = [1,2,4]

In [72]:
np.equal(a,b)

array([False, False, False])

In [71]:
np.equal(a,c)

array([ True,  True, False])

### Aggregate FUnctions

In [74]:
a = [1,2,3]
b = [2,3,4]
c = [1,2,4]

print("MIn : ",np.min(b))
print("Minimum : ",np.minimum(b,c))  # comparing 2 arrays and return a new array containing the element wise minimum
print("Maximum: ",np.maximum(b,c))
print("Mean: ",np.mean(a))
print("Median: ",np.median(b))
print("Standard Deviation: ",np.std(a))
print("Variance: ",np.var(a))

MIn :  2
Minimum :  [1 2 4]
Maximum:  [2 3 4]
Mean:  2.0
Median:  3.0
Standard Deviation:  0.816496580927726
Variance:  0.6666666666666666


In [76]:
np.sqrt(0.6666666666666666)   # std is square root of variance

0.816496580927726

In [77]:
shape = (3,4,5)

In [79]:
x = np.zeros(shape)

In [80]:
x.ndim

3

In [81]:
x.shape

(3, 4, 5)

In [82]:
x.dtype

dtype('float64')

In [83]:
x.size

60

## Indexing and Slicing

In [85]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a[0]

array([1, 2, 3])

In [88]:
a[1]

array([4, 5, 6])

In [89]:
a[:1]

array([[1, 2, 3]])

In [90]:
a[:1,1:]      # a[0:0 , 1:2]

array([[2, 3]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

        0  1  2
      0 [10, 20, 30]
      1 [40, 50, 60]
      2 [70, 80, 90]

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [98]:
a.shape

(3, 3)

In [92]:
# a[rows       , columns]
# a[start:stop , start, stop]
# a[start:stop-1:start,stop-1]
# if nothing is mentioned in the start there will be 0
# if nothing is mention in the stop then it will be replaced with end index of the array wea re operating upon
a[:2 , 1:]    #a[0:1(stop-1) , 1:2]

array([[2, 3],
       [5, 6]])

In [97]:
a[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

In [94]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
a[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

         0  1  2
      0 [1, 2, 3]
      1 [4, 5, 6]
      2 [7, 8, 9]

In [99]:
a[:,:]    # a[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
a[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
a.shape

(3, 3)

In [101]:
a[1: , 1:]  ->  # a[1:3 , 1:3]    -> # a[1:2(stop-1) , 1:2(stop-1)]

array([[5, 6],
       [8, 9]])

In [103]:
a[1:3 , 1:2]   # a[1:1 , 1:1]

array([[5]])

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
[[4, 5],
[7, 8]]

In [110]:
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [109]:
a[1:3 , 0:2]  

array([[4, 5],
       [7, 8]])

## Array Manipulation

In [112]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [113]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [114]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [115]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
arr = np.arange(16 , dtype = int).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Advantages of Numpy Array over list

In [129]:
my_list = [1,2,3,4,5]

squared_list = [x**2 for x in my_list]
print(squared_list)

[1, 4, 9, 16, 25]


In [130]:
my_array = np.array([1,2,3,4,5])
squared_array = np.square(my_array)
print(squared_array)

[ 1  4  9 16 25]


In [134]:
import time

In [133]:
def using_list():
    t1 = time.time()
    X = range(100000)
    Y = range(100000)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def using_Numpy():
    t2 = time.time()
    A = np.arange(190000)
    B = np.arange(190000)
    C = A+B
    return time.time() - t2

list_time = using_list()
array_time = using_Numpy()

print(list_time , array_time)
print("Numpy is : "+str(list_time/array_time)+"times faster then list ")

0.041472434997558594 0.00469207763671875
Numpy is : 8.838821138211381times faster then list 


In [136]:
pwd

'C:\\Users\\shant\\Desktop'